apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QVNJQVk1RkFRUkpTRlBDMkxCV0kK
  aws_secret_access_key: RGlXNjRDRi82N09nVFNEbEs1WlcxNG5RY3c5Z2ZLK2xUc3NYRkt6Kwo=
