language: node_js
node_js:
  - 16

services:
  - docker
#building
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

#tagging
  - docker tag udagram-api-feed codart7/udagram-api-feed:v2
  - docker tag udagram-api-user codart7/udagram-api-user:v2
  - docker tag udagram-frontend codart7/udagram-frontend:v2
  - docker tag reverseproxy codart7y/reverseproxy:v2

#pushing
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push codart7/udagram-api-feed:v3
  - docker push codart7/udagram-api-user:v3
  - docker push codart7/udagram-frontend:v3
  - docker push codart7/reverseproxy:latest
